{{- if .Values.podDisruptionBudget.enabled }}
---
# OpenLDAP PodDisruptionBudget
{{- if .Values.openldap.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ldap-stack.openldap.fullname" . }}
  labels:
    {{- include "ldap-stack.openldap.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ldap-stack.openldap.selectorLabels" . | nindent 6 }}
{{- end }}
---
# Keycloak PodDisruptionBudget
{{- if .Values.keycloak.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ldap-stack.keycloak.fullname" . }}
  labels:
    {{- include "ldap-stack.keycloak.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ldap-stack.keycloak.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
